### REGISTER
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "fullName": "Leah Achi",
  "email": "rachaela2610@gmail.com",
  "phone": "0705607227",
  "password": "Password123",
  "confirmPassword": "Password123"
}

### LOGIN
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "olaachieng@gmail.com",
  "password": "Password123"
}


### GET ALL USERS
GET http://localhost:3000/auth/users
