### REGISTER
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "fullName": "John Doe",
  "email": "john@example.com",
  "phone": "0712345678",
  "password": "securePass123",
  "confirmPassword": "securePass123"
}

### LOGIN
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "john@example.com",
  "password": "securePass123"
}


### GET ALL USERS
GET http://localhost:3000/auth/users
