### Admin Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "olaachieng123@gmail.com",
  "password": "Admin123"
}

### Create Category
POST http://localhost:3000/products/categories
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoib2xhYWNoaWVuZzEyM0BnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NTA2MDA0MjksImV4cCI6MTc1MDY4NjgyOX0.J8f1-5ZwN8el1EfE6o9CCc_jWIxSLmMESbQRo-Yk2lA
Content-Type: application/json

{
  "name": "Accessories new"
}

### Get All Categories
GET http://localhost:3000/products/categories/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoib2xhYWNoaWVuZzEyM0BnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NTA3MzU2MjcsImV4cCI6MTc1MDgyMjAyN30.Qhorw84pZliUUCc_4dTbNFmtBBGxPnNVvdj9K31gvwE


### Post a Product
POST http://localhost:3000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoib2xhYWNoaWVuZzEyM0BnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NTA2MDA0MjksImV4cCI6MTc1MDY4NjgyOX0.J8f1-5ZwN8el1EfE6o9CCc_jWIxSLmMESbQRo-Yk2lA
Content-Type: application/json

{
  "name": "Elegant Crochet Bag",
  "description": "Spacious and stylish handmade crochet tote bag.",
  "price": 2500,
  "stock": 10,
  "sale": true,
  "salePrice": 2000,
  "isNew": true,
  "isHot": true,
  "isTrending": false,
  "categoryIds": [1, 4],
  "imageUrls": [
    "https://images.unsplash.com/photo-1589739903200-74a81c8b9d89",
    "https://images.unsplash.com/photo-1605266172335-0f7e1ff291b7"
  ]
}


### Get All Products
GET http://localhost:3000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoib2xhYWNoaWVuZzEyM0BnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NTA3OTA3OTcsImV4cCI6MTc1MDg3NzE5N30.13Pt1DPLzYZq2V5y2_-IRrjFwWv-FgF0PAAJKpuOu6Y

### Get Single Product by ID
GET http://localhost:3000/products/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoib2xhYWNoaWVuZzEyM0BnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NTA2MDA0MjksImV4cCI6MTc1MDY4NjgyOX0.J8f1-5ZwN8el1EfE6o9CCc_jWIxSLmMESbQRo-Yk2lA

### Update Product
PATCH http://localhost:3000/products/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoib2xhYWNoaWVuZzEyM0BnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NTA2MDA0MjksImV4cCI6MTc1MDY4NjgyOX0.J8f1-5ZwN8el1EfE6o9CCc_jWIxSLmMESbQRo-Yk2lA
Content-Type: application/json

{
  "name": "Updated Crochet Bag",
  "description": "Updated description with even better detail.",
  "price": 2500,
  "stock": 10,
  "sale": false,
  "salePrice": null,
  "isNew": false,
  "isHot": true,
  "isTrending": false,
  "categoryIds": ["4"],
  "imageUrls": [
    "https://example.com/images/updated1.jpg"
  ]
}

### Delete Image by ID
DELETE http://localhost:3000/products/image/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoib2xhYWNoaWVuZzEyM0BnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NTA2MDA0MjksImV4cCI6MTc1MDY4NjgyOX0.J8f1-5ZwN8el1EfE6o9CCc_jWIxSLmMESbQRo-Yk2lA

### Delete a product by ID
DELETE http://localhost:3000/products/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoib2xhYWNoaWVuZzEyM0BnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NTA2MDA0MjksImV4cCI6MTc1MDY4NjgyOX0.J8f1-5ZwN8el1EfE6o9CCc_jWIxSLmMESbQRo-Yk2lA
